# This is a config for E2B sandbox template.
# You can use template ID (izn0c1k29ehg40ycymp1) or template name (nextjs-app-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs-app-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-app-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-app-test')

team_id = "0cc2c3b3-68fb-4cd7-a6b2-ee04a8942d7a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-app-test"
template_id = "izn0c1k29ehg40ycymp1"
